version: '3.8'
services:
  app:
    container_name: zieglerlabs-recipes
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_URI: mongodb://root:password@db:27017
      PORT: 4000
    ports:
      - '4000:4000'
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
